### ISSUE TITLE
New features in SSP 2.0

### ISSUE THREAD

**Issue by DagBruck** [modelica/ssp-standard#40]
I think it would be valuable to summarize the new features in SSP 2.0 as a short bullet list. I need that internally, and it will be needed for the announcement. Maybe we can start now.
* Support for FMI 3
    * Basic types, such as Float32.
    * Scheduled execution (component implementation attribute).
    * Clocked signals.
    * Array connectors.
* Optional inner view connector coordinates (wen inner view is different from outer view).
* Initial meta-data support from "SSP Traceability" project.
* Optional support for representing Modelica components and connectors in SSP.
* Clarifications and bug fixes.

**Comment by JochenKoehler** [comment]
web meeting 2024-08-13:
As a starting point for review (of changes / diffs): https://github.com/modelica/ssp-standard/releases/tag/untagged-a425b2e7f63c982b9ef3
New pull request should be created with the "extended" bullet list from above.

**Comment by robha67** [comment]
@pmai I am trying to push the minor changes I made to the branch that you created but I am running into problems. I get the error "permission to modelica/ssp-standard.git denied to robha67." Do I have the correct access rights?

**Comment by robha67** [comment]
@pmai I cannot find any pull request that allows for, for example, arrays in SSV files. Was that added to the 2.0 specification?

**Comment by pmai** [comment]
> @pmai I cannot find any pull request that allows for, for example, arrays in SSV files. Was that added to the 2.0 specification?

PR #8 contains commit 2d4b9460 that adds the array capabilities to SSV.

**Comment by pmai** [comment]
> @pmai I am trying to push the minor changes I made to the branch that you created but I am running into problems. I get the error "permission to modelica/ssp-standard.git denied to robha67." Do I have the correct access rights?

From the access rights point of view you should be able to push to the ssp-standard repo, so it should work to push new commits on top of the current branch. If it does not work out for you, you might want to see if pushing to your own fork of ssp-standard works...

**Comment by robha67** [comment]
@pmai just to avoid any further confusion. Should the text be added to 1__overview.adoc instead of the 0__preamble.adoc?

**Comment by pmai** [comment]
> @pmai just to avoid any further confusion. Should the text be added to 1__overview.adoc instead of the 0__preamble.adoc?

Yes, that is the idea; I have now consolidated the two sets of descriptions somewhat, tightened up the language to avoid future or past-looking statements, and added some related changes to the PR/branch, which can now serve as a basis for your further changes.

**Comment by robha67** [comment]
@pmai Again, just to be sure, the PR branch is "[maint/add-20-changes](https://github.com/modelica/ssp-standard/tree/maint/add-20-changes)"?

**Comment by pmai** [comment]
> @pmai Again, just to be sure, the PR branch is "[maint/add-20-changes](https://github.com/modelica/ssp-standard/tree/maint/add-20-changes)"?

Yes.

**Comment by Hans-Martin-Heinkel** [comment]
Checked the text, no additional comments from my side

**Comment by pmai** [comment]
Closed via #43
