### ISSUE TITLE
Version attribute of SSP 2.0 does not allow to import SSP 1.0 files

### ISSUE THREAD

**Issue by UKiffmeier** [modelica/ssp-standard#41]
The result of https://github.com/modelica/ssp-standard/issues/39 was that the SSP 2.0 schema is compatible to the SSP 1.0 schema with the only exception, that it does not allow the value "1.0" for the SystemStructureDescription.version attribute.

This means that the version attribute in existing SSD 1.0 files must be changed to "2.0-alpha", or later "2.0".

In many cases, it is not wanted, that an existing SSP 1.0 file (possibly under version control) must be changed and an SSP 1.0 container must be re-generated to be used in a SSP 2.0 tool.

Therefore, the proposal is to change the pattern for the SSP 2.0 version attribute from
>    2[.][0-9]+(-.+) 

to

>    [1-2][.][0-9]+(-.+)?

This new pattern allows "1.0", "2.0", "2.0-alpha" and makes the postfix optional.

**Comment by pmai** [comment]
Yes this would be the goal after we have now verified the backward compatibility, and we go to the release (and the postfix would then be prohibited, to not accidentally accept non-released files). Prior to release the prefix is required, to prevent accidents.
