### ISSUE TITLE
Editorial problems in the SSP 2.0 draft documentation

### ISSUE THREAD

**Issue by UKiffmeier** [modelica/ssp-standard#47]
During the last days I have reviewed the current version of the SSP 2.0 documentation and found some editorial problems. The problems mainly concern: 

* The description of the attribute MetaData.source and MetaData.sourceBase [section 4.5.4]
* Duplicate description texts [section 5.1, section 5.2.1]

See comments in the attached PDF file.
[SystemStructureAndParameterization20-alpha.2024-10-15.Review.pdf](https://github.com/user-attachments/files/17517078/SystemStructureAndParameterization20-alpha.2024-10-15.Review.pdf)
Some if the comments in the PDF were already solved by Pierre's [PR #44](https://github.com/modelica/ssp-standard/pull/44) and  [PR #45](https://github.com/modelica/ssp-standard/pull/45).

**Comment by UKiffmeier** [comment]
I have created pull request #48 with possible fixes for the above mentioned problems.

**Comment by beutlich** [comment]
Can this be closed after #48 got closed?

**Comment by UKiffmeier** [comment]
I will close this issue since all findings are addressed with PR #44, PR #45, and PR #48.  
@beutlich : FYI.
