### ISSUE TITLE
Where can SSP 1.0.1 standard be obtained?

### ISSUE THREAD

**Issue by beutlich** [modelica/ssp-standard#7]
SSP 1.0.1 was accepted by MA on 2022-08-10. However, the updated standard document is neither available as [release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) asset here on GitHub nor announced nor [published](https://ssp-standard.org/downloads/) at the official website.

**Comment by pmai** [comment]
Yes that got delayed due to the web page redesign efforts. The 1.0.1 standard should now be available at the main page as intended...
